{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:  
    {{- include "hello-world.labels" . | nindent 4 }}
  annotations:
    {{- range $key, $value := .Values.route.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  port:
    targetPort: {{ .Values.service.targetPort }}
  to:
    kind: Service
    name: {{ include "hello-world.fullname" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
